project:
  type: default
  output-dir: _site
  render:
    - index.qmd

format:
  revealjs:
    theme:
      - simple
      - theme.scss
    logo: images/reborn-engineer.png
    width: 1280
    height: 720
    margin: 0.08
    center: false
    slide-level: 2
    slide-number: c/t
    transition: none
    incremental: false
    navigation-mode: linear
    history: true
